/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "book_constants.h"

namespace example {

const bookConstants g_book_constants;

bookConstants::bookConstants() {
}

} // namespace

