/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef BookServlet_H
#define BookServlet_H

#include <thrift/TDispatchProcessor.h>
#include "rpc_types.h"

namespace example {

class BookServletIf {
 public:
  virtual ~BookServletIf() {}
  virtual bool Sender(const std::vector< ::example::Book_Info> & books) = 0;
  virtual void Sender2(const std::vector< ::example::Book_Info> & books) = 0;
};

class BookServletIfFactory {
 public:
  typedef BookServletIf Handler;

  virtual ~BookServletIfFactory() {}

  virtual BookServletIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(BookServletIf* /* handler */) = 0;
};

class BookServletIfSingletonFactory : virtual public BookServletIfFactory {
 public:
  BookServletIfSingletonFactory(const boost::shared_ptr<BookServletIf>& iface) : iface_(iface) {}
  virtual ~BookServletIfSingletonFactory() {}

  virtual BookServletIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(BookServletIf* /* handler */) {}

 protected:
  boost::shared_ptr<BookServletIf> iface_;
};

class BookServletNull : virtual public BookServletIf {
 public:
  virtual ~BookServletNull() {}
  bool Sender(const std::vector< ::example::Book_Info> & /* books */) {
    bool _return = false;
    return _return;
  }
  void Sender2(const std::vector< ::example::Book_Info> & /* books */) {
    return;
  }
};

typedef struct _BookServlet_Sender_args__isset {
  _BookServlet_Sender_args__isset() : books(false) {}
  bool books :1;
} _BookServlet_Sender_args__isset;

class BookServlet_Sender_args {
 public:

  static const char* ascii_fingerprint; // = "3FF1D47D76AF116EF557F3DDAD4D6E00";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0xF1,0xD4,0x7D,0x76,0xAF,0x11,0x6E,0xF5,0x57,0xF3,0xDD,0xAD,0x4D,0x6E,0x00};

  BookServlet_Sender_args(const BookServlet_Sender_args&);
  BookServlet_Sender_args& operator=(const BookServlet_Sender_args&);
  BookServlet_Sender_args() {
  }

  virtual ~BookServlet_Sender_args() throw();
  std::vector< ::example::Book_Info>  books;

  _BookServlet_Sender_args__isset __isset;

  void __set_books(const std::vector< ::example::Book_Info> & val);

  bool operator == (const BookServlet_Sender_args & rhs) const
  {
    if (!(books == rhs.books))
      return false;
    return true;
  }
  bool operator != (const BookServlet_Sender_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BookServlet_Sender_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const BookServlet_Sender_args& obj);
};


class BookServlet_Sender_pargs {
 public:

  static const char* ascii_fingerprint; // = "3FF1D47D76AF116EF557F3DDAD4D6E00";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0xF1,0xD4,0x7D,0x76,0xAF,0x11,0x6E,0xF5,0x57,0xF3,0xDD,0xAD,0x4D,0x6E,0x00};


  virtual ~BookServlet_Sender_pargs() throw();
  const std::vector< ::example::Book_Info> * books;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const BookServlet_Sender_pargs& obj);
};

typedef struct _BookServlet_Sender_result__isset {
  _BookServlet_Sender_result__isset() : success(false) {}
  bool success :1;
} _BookServlet_Sender_result__isset;

class BookServlet_Sender_result {
 public:

  static const char* ascii_fingerprint; // = "D9D3B4421B1F23CB4063C80B484E7909";
  static const uint8_t binary_fingerprint[16]; // = {0xD9,0xD3,0xB4,0x42,0x1B,0x1F,0x23,0xCB,0x40,0x63,0xC8,0x0B,0x48,0x4E,0x79,0x09};

  BookServlet_Sender_result(const BookServlet_Sender_result&);
  BookServlet_Sender_result& operator=(const BookServlet_Sender_result&);
  BookServlet_Sender_result() : success(0) {
  }

  virtual ~BookServlet_Sender_result() throw();
  bool success;

  _BookServlet_Sender_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const BookServlet_Sender_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const BookServlet_Sender_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BookServlet_Sender_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const BookServlet_Sender_result& obj);
};

typedef struct _BookServlet_Sender_presult__isset {
  _BookServlet_Sender_presult__isset() : success(false) {}
  bool success :1;
} _BookServlet_Sender_presult__isset;

class BookServlet_Sender_presult {
 public:

  static const char* ascii_fingerprint; // = "D9D3B4421B1F23CB4063C80B484E7909";
  static const uint8_t binary_fingerprint[16]; // = {0xD9,0xD3,0xB4,0x42,0x1B,0x1F,0x23,0xCB,0x40,0x63,0xC8,0x0B,0x48,0x4E,0x79,0x09};


  virtual ~BookServlet_Sender_presult() throw();
  bool* success;

  _BookServlet_Sender_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const BookServlet_Sender_presult& obj);
};

typedef struct _BookServlet_Sender2_args__isset {
  _BookServlet_Sender2_args__isset() : books(false) {}
  bool books :1;
} _BookServlet_Sender2_args__isset;

class BookServlet_Sender2_args {
 public:

  static const char* ascii_fingerprint; // = "3FF1D47D76AF116EF557F3DDAD4D6E00";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0xF1,0xD4,0x7D,0x76,0xAF,0x11,0x6E,0xF5,0x57,0xF3,0xDD,0xAD,0x4D,0x6E,0x00};

  BookServlet_Sender2_args(const BookServlet_Sender2_args&);
  BookServlet_Sender2_args& operator=(const BookServlet_Sender2_args&);
  BookServlet_Sender2_args() {
  }

  virtual ~BookServlet_Sender2_args() throw();
  std::vector< ::example::Book_Info>  books;

  _BookServlet_Sender2_args__isset __isset;

  void __set_books(const std::vector< ::example::Book_Info> & val);

  bool operator == (const BookServlet_Sender2_args & rhs) const
  {
    if (!(books == rhs.books))
      return false;
    return true;
  }
  bool operator != (const BookServlet_Sender2_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BookServlet_Sender2_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const BookServlet_Sender2_args& obj);
};


class BookServlet_Sender2_pargs {
 public:

  static const char* ascii_fingerprint; // = "3FF1D47D76AF116EF557F3DDAD4D6E00";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0xF1,0xD4,0x7D,0x76,0xAF,0x11,0x6E,0xF5,0x57,0xF3,0xDD,0xAD,0x4D,0x6E,0x00};


  virtual ~BookServlet_Sender2_pargs() throw();
  const std::vector< ::example::Book_Info> * books;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const BookServlet_Sender2_pargs& obj);
};

class BookServletClient : virtual public BookServletIf {
 public:
  BookServletClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  BookServletClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool Sender(const std::vector< ::example::Book_Info> & books);
  void send_Sender(const std::vector< ::example::Book_Info> & books);
  bool recv_Sender();
  void Sender2(const std::vector< ::example::Book_Info> & books);
  void send_Sender2(const std::vector< ::example::Book_Info> & books);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class BookServletProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<BookServletIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (BookServletProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_Sender(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_Sender2(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  BookServletProcessor(boost::shared_ptr<BookServletIf> iface) :
    iface_(iface) {
    processMap_["Sender"] = &BookServletProcessor::process_Sender;
    processMap_["Sender2"] = &BookServletProcessor::process_Sender2;
  }

  virtual ~BookServletProcessor() {}
};

class BookServletProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  BookServletProcessorFactory(const ::boost::shared_ptr< BookServletIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< BookServletIfFactory > handlerFactory_;
};

class BookServletMultiface : virtual public BookServletIf {
 public:
  BookServletMultiface(std::vector<boost::shared_ptr<BookServletIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~BookServletMultiface() {}
 protected:
  std::vector<boost::shared_ptr<BookServletIf> > ifaces_;
  BookServletMultiface() {}
  void add(boost::shared_ptr<BookServletIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  bool Sender(const std::vector< ::example::Book_Info> & books) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Sender(books);
    }
    return ifaces_[i]->Sender(books);
  }

  void Sender2(const std::vector< ::example::Book_Info> & books) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Sender2(books);
    }
    ifaces_[i]->Sender2(books);
  }

};

} // namespace

#endif
