/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "book_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace example {


Book_Info::~Book_Info() throw() {
}


void Book_Info::__set_book_id(const int32_t val) {
  this->book_id = val;
}

void Book_Info::__set_book_name(const std::string& val) {
  this->book_name = val;
}

void Book_Info::__set_book_author(const std::string& val) {
  this->book_author = val;
}

void Book_Info::__set_book_price(const double val) {
  this->book_price = val;
}

void Book_Info::__set_book_publisher(const std::string& val) {
  this->book_publisher = val;
}

const char* Book_Info::ascii_fingerprint = "5336EE826747522DE4E4045EA4440B86";
const uint8_t Book_Info::binary_fingerprint[16] = {0x53,0x36,0xEE,0x82,0x67,0x47,0x52,0x2D,0xE4,0xE4,0x04,0x5E,0xA4,0x44,0x0B,0x86};

uint32_t Book_Info::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->book_id);
          this->__isset.book_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->book_name);
          this->__isset.book_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->book_author);
          this->__isset.book_author = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->book_price);
          this->__isset.book_price = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->book_publisher);
          this->__isset.book_publisher = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Book_Info::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("Book_Info");

  xfer += oprot->writeFieldBegin("book_id", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->book_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("book_name", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->book_name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("book_author", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->book_author);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("book_price", ::apache::thrift::protocol::T_DOUBLE, 4);
  xfer += oprot->writeDouble(this->book_price);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("book_publisher", ::apache::thrift::protocol::T_STRING, 5);
  xfer += oprot->writeString(this->book_publisher);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(Book_Info &a, Book_Info &b) {
  using ::std::swap;
  swap(a.book_id, b.book_id);
  swap(a.book_name, b.book_name);
  swap(a.book_author, b.book_author);
  swap(a.book_price, b.book_price);
  swap(a.book_publisher, b.book_publisher);
  swap(a.__isset, b.__isset);
}

Book_Info::Book_Info(const Book_Info& other0) {
  book_id = other0.book_id;
  book_name = other0.book_name;
  book_author = other0.book_author;
  book_price = other0.book_price;
  book_publisher = other0.book_publisher;
  __isset = other0.__isset;
}
Book_Info& Book_Info::operator=(const Book_Info& other1) {
  book_id = other1.book_id;
  book_name = other1.book_name;
  book_author = other1.book_author;
  book_price = other1.book_price;
  book_publisher = other1.book_publisher;
  __isset = other1.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const Book_Info& obj) {
  using apache::thrift::to_string;
  out << "Book_Info(";
  out << "book_id=" << to_string(obj.book_id);
  out << ", " << "book_name=" << to_string(obj.book_name);
  out << ", " << "book_author=" << to_string(obj.book_author);
  out << ", " << "book_price=" << to_string(obj.book_price);
  out << ", " << "book_publisher=" << to_string(obj.book_publisher);
  out << ")";
  return out;
}

} // namespace
