/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef book_CONSTANTS_H
#define book_CONSTANTS_H

#include "book_types.h"

namespace example {

class bookConstants {
 public:
  bookConstants();

};

extern const bookConstants g_book_constants;

} // namespace

#endif
